runtime: python313
entrypoint: gunicorn bycco.main:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT

env_variables:
  FILESTORE_BUCKET: byccowebsiteprod.appspot.com
  GOOGLE_PROJECT_ID: byccowebsiteprod
  GOOGLE_CLIENT_ID: 464711449307-7j2oecn3mkfs1eh3o7b5gh8np3ebhrdp.apps.googleusercontent.com
  TZ: Europe/Brussels

handlers:
  - url: /api/.*
    script: auto
    secure: always

  - url: /docs
    script: auto
    secure: always

  - url: /openapi.json
    script: auto
    secure: always

  - url: /(.*\..+)$
    static_files: dist/\1
    upload: dist/(.*\..+)$
    secure: always

  - url: /
    static_files: dist/index.html
    secure: always
    upload: dist/index.html

  - url: /([^\.]*)$
    static_files: dist/\1/index.html
    upload: dist/([^\.]*)/index.html
    secure: always

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
